version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
