name: Deploy workers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/main/workers/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          preCommands: cd src/main/workers && npm install .
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish --env production
        env:
          REALM_APPID: ${{ secrets.REALM_APPID }}
          MONGO_API_KEY: ${{ secrets.MONGO_API_KEY }}