name: Deploy workers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/main/workers/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish mongo-proxy
        uses: cloudflare/wrangler-action@v3.3.0
        with:
          preCommands: cd src/main/workers/api && npm install .
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish --env production --var REALM_APPID:${{ secrets.REALM_APPID }} --var MONGO_API_KEY:${{ secrets.MONGO_API_KEY }}
      - name: Publish prerender
        uses: cloudflare/wrangler-action@v3.3.0
        with:
          preCommands: cd src/main/workers/prerender && npm install .
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish --env production --var API_KEY:${{ secrets.PRERENDER_API_KEY }}