name: Fetch API

on: [ workflow_dispatch ]

jobs:
  fetch-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -f docker/Dockerfile -t starrylines_${{ github.sha }} . --no-cache
      - name: Run
        run: |
          docker run -e 'GITHUB_TOKEN= ${{ secrets.GITHUB_TOKEN }}' -e 'MONGO_SECRET=${{ secrets.MONGO_SECRET }}' -e 'MONGO_USER=${{ secrets.MONGO_USER }}' -e 'MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }}' -e 'MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}' starrylines_${{ github.sha }} fetch all
