name: Fetch GH API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  getloc:
    uses: PabloLec/StarryLines/.github/workflows/run.yml@main
    with:
      args: 'fetch all'
    secrets: inherit