name: Fetch GH API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  getloc:
    steps:
      - uses: run PabloLec/StarryLines/.github/workflows/run.yml@main
        with:
          args: 'fetch all'