name: Fetch GH API

on:
  workflow_dispatch:
  schedule:
    - cron: '45 1,11,20 * * *'

jobs:
  fetch:
    uses: PabloLec/StarryLines/.github/workflows/run.yml@main
    with:
      args: 'fetch all'
    secrets:
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_SECRET: ${{ secrets.MONGO_SECRET }}
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
      MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}