name: Get LoC - Go

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  getloc:
    uses: PabloLec/StarryLines/.github/workflows/run.yml@main
    with:
      args: 'getloc go'
    secrets: inherit