name: Get LoC - Javascript

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  getloc:
    uses: run PabloLec/StarryLines/.github/workflows/run.yml@main
    with:
      args: 'getloc javascript'