name: PR tests

on:
  pull_request_target:
    branches:
      - main
      - develop

jobs:
  approve:
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    environment:
      name: PR-env
    steps:
      - name: Approve
        run: echo "Test run needs approval"

  PR-tests:
    needs: [approve]
    if: always()
    uses: PabloLec/StarryLines/.github/workflows/tests.yml@main
    secrets:
      MONGO_USER_TEST: ${{ secrets.MONGO_USER_TEST }}
      MONGO_SECRET_TEST: ${{ secrets.MONGO_SECRET_TEST }}
      MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
      MONGO_DATABASE_TEST: ${{ secrets.MONGO_DATABASE_TEST }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
